# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/search-find-qgis-plugin/find_location/zip_build/find_location/gui/find_location_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindLocationDockWidgetBase(object):
    def setupUi(self, FindLocationDockWidgetBase):
        FindLocationDockWidgetBase.setObjectName("FindLocationDockWidgetBase")
        FindLocationDockWidgetBase.resize(979, 613)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 977, 592))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.vboxlayout.setObjectName("vboxlayout")
        self.geMainLayout = QtWidgets.QVBoxLayout()
        self.geMainLayout.setObjectName("geMainLayout")
        self.vboxlayout.addLayout(self.geMainLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        FindLocationDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(FindLocationDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(FindLocationDockWidgetBase)

    def retranslateUi(self, FindLocationDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        FindLocationDockWidgetBase.setWindowTitle(_translate("FindLocationDockWidgetBase", "Find Location"))
