# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/qgis-gnavs-plugin/gnavs/gui/measurement/aggregation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(935, 560)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mGroupBox = gui.QgsCollapsibleGroupBox(Form)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 25, 5, 5)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.mGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lfbGPSCountBest = QtWidgets.QLabel(self.mGroupBox)
        self.lfbGPSCountBest.setObjectName("lfbGPSCountBest")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lfbGPSCountBest)
        self.label_5 = QtWidgets.QLabel(self.mGroupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lfbGPSLon = QtWidgets.QLabel(self.mGroupBox)
        self.lfbGPSLon.setObjectName("lfbGPSLon")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lfbGPSLon)
        self.label_10 = QtWidgets.QLabel(self.mGroupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lfbGPSLat = QtWidgets.QLabel(self.mGroupBox)
        self.lfbGPSLat.setObjectName("lfbGPSLat")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lfbGPSLat)
        self.label_6 = QtWidgets.QLabel(self.mGroupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lfbGPSsatCount = QtWidgets.QLabel(self.mGroupBox)
        self.lfbGPSsatCount.setObjectName("lfbGPSsatCount")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lfbGPSsatCount)
        self.label_7 = QtWidgets.QLabel(self.mGroupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lfbGPSvDop = QtWidgets.QLabel(self.mGroupBox)
        self.lfbGPSvDop.setObjectName("lfbGPSvDop")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lfbGPSvDop)
        self.label_8 = QtWidgets.QLabel(self.mGroupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lfbGPShDop = QtWidgets.QLabel(self.mGroupBox)
        self.lfbGPShDop.setObjectName("lfbGPShDop")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lfbGPShDop)
        self.label_9 = QtWidgets.QLabel(self.mGroupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lfbGPSpDop = QtWidgets.QLabel(self.mGroupBox)
        self.lfbGPSpDop.setObjectName("lfbGPSpDop")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lfbGPSpDop)
        self.line = QtWidgets.QFrame(self.mGroupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.line)
        self.label = QtWidgets.QLabel(self.mGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lfbGPSDevice = QtWidgets.QLineEdit(self.mGroupBox)
        self.lfbGPSDevice.setObjectName("lfbGPSDevice")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lfbGPSDevice)
        self.label_2 = QtWidgets.QLabel(self.mGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lfbGPSName = QtWidgets.QLineEdit(self.mGroupBox)
        self.lfbGPSName.setObjectName("lfbGPSName")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lfbGPSName)
        self.label_3 = QtWidgets.QLabel(self.mGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lfbGPSDescription = QtWidgets.QPlainTextEdit(self.mGroupBox)
        self.lfbGPSDescription.setObjectName("lfbGPSDescription")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lfbGPSDescription)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.mGroupBox)
        self.lfbAddToMapWidget = QtWidgets.QWidget(Form)
        self.lfbAddToMapWidget.setObjectName("lfbAddToMapWidget")
        self.lfbAddToMapLayout = QtWidgets.QHBoxLayout(self.lfbAddToMapWidget)
        self.lfbAddToMapLayout.setObjectName("lfbAddToMapLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lfbAddToMapLayout.addItem(spacerItem)
        self.lfbAddToMapBtn = QtWidgets.QPushButton(self.lfbAddToMapWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbAddToMapBtn.sizePolicy().hasHeightForWidth())
        self.lfbAddToMapBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.lfbAddToMapBtn.setFont(font)
        self.lfbAddToMapBtn.setStyleSheet("QPushButton{\n"
"    border: 2px solid #333;\n"
"    color: #555;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: yellow;\n"
"}\n"
"QPushButton:enabled{\n"
"    border:  2px solid green;\n"
"    background-color: green;\n"
"    color: #fff;\n"
"}")
        self.lfbAddToMapBtn.setObjectName("lfbAddToMapBtn")
        self.lfbAddToMapLayout.addWidget(self.lfbAddToMapBtn)
        self.verticalLayout.addWidget(self.lfbAddToMapWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mGroupBox.setTitle(_translate("Form", "Details"))
        self.label_4.setText(_translate("Form", "Best Measurements"))
        self.lfbGPSCountBest.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "Longitude"))
        self.lfbGPSLon.setText(_translate("Form", "0"))
        self.label_10.setText(_translate("Form", "Latitude"))
        self.lfbGPSLat.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "Satelite Count"))
        self.lfbGPSsatCount.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "VDOP"))
        self.lfbGPSvDop.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "HDOP"))
        self.lfbGPShDop.setText(_translate("Form", "0"))
        self.label_9.setText(_translate("Form", "PDOP"))
        self.lfbGPSpDop.setText(_translate("Form", "0"))
        self.label.setText(_translate("Form", "GPS-Gerät"))
        self.label_2.setText(_translate("Form", "Punktname / ID"))
        self.label_3.setText(_translate("Form", "Bemerkung"))
        self.lfbAddToMapBtn.setText(_translate("Form", "ADD TO MAP"))
from qgis import gui
