# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/qgis-gnavs-plugin/gnavs/gui/recording/recording.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1007, 401)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lfbRecording = QtWidgets.QVBoxLayout()
        self.lfbRecording.setContentsMargins(-1, 0, -1, 0)
        self.lfbRecording.setObjectName("lfbRecording")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lfbRecording.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lfbValidIndicator = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbValidIndicator.sizePolicy().hasHeightForWidth())
        self.lfbValidIndicator.setSizePolicy(sizePolicy)
        self.lfbValidIndicator.setMinimumSize(QtCore.QSize(10, 10))
        self.lfbValidIndicator.setStyleSheet("background-color: #f0f;\n"
"border-radius: 5px;")
        self.lfbValidIndicator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lfbValidIndicator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lfbValidIndicator.setObjectName("lfbValidIndicator")
        self.horizontalLayout_2.addWidget(self.lfbValidIndicator)
        self.lfbSerialPortList = QtWidgets.QComboBox(Form)
        self.lfbSerialPortList.setObjectName("lfbSerialPortList")
        self.horizontalLayout_2.addWidget(self.lfbSerialPortList)
        self.lfbRefreshSerialListBtn = QtWidgets.QToolButton(Form)
        self.lfbRefreshSerialListBtn.setEnabled(False)
        self.lfbRefreshSerialListBtn.setText("")
        self.lfbRefreshSerialListBtn.setObjectName("lfbRefreshSerialListBtn")
        self.horizontalLayout_2.addWidget(self.lfbRefreshSerialListBtn)
        self.lfbCancelCoordinatesBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbCancelCoordinatesBtn.sizePolicy().hasHeightForWidth())
        self.lfbCancelCoordinatesBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lfbCancelCoordinatesBtn.setFont(font)
        self.lfbCancelCoordinatesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbCancelCoordinatesBtn.setStyleSheet("QPushButton{\n"
"    border: 2px solid #333;\n"
"    color: #555;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: yellow;\n"
"}\n"
"QPushButton:enabled{\n"
"    border: 2px solid orange;\n"
"    background-color: orange;\n"
"    color: #000;\n"
"}")
        self.lfbCancelCoordinatesBtn.setObjectName("lfbCancelCoordinatesBtn")
        self.horizontalLayout_2.addWidget(self.lfbCancelCoordinatesBtn)
        self.lfbGetCoordinatesGtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbGetCoordinatesGtn.sizePolicy().hasHeightForWidth())
        self.lfbGetCoordinatesGtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lfbGetCoordinatesGtn.setFont(font)
        self.lfbGetCoordinatesGtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbGetCoordinatesGtn.setStyleSheet("QPushButton{\n"
"    border: 2px solid #333;\n"
"    color: #555;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: yellow;\n"
"}\n"
"QPushButton:enabled{\n"
"    border:  2px solid green;\n"
"    background-color: green;\n"
"    color: #fff;\n"
"}")
        self.lfbGetCoordinatesGtn.setObjectName("lfbGetCoordinatesGtn")
        self.horizontalLayout_2.addWidget(self.lfbGetCoordinatesGtn)
        self.lfbRecording.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.geConnectionInfoLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geConnectionInfoLabel.sizePolicy().hasHeightForWidth())
        self.geConnectionInfoLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.geConnectionInfoLabel.setFont(font)
        self.geConnectionInfoLabel.setWordWrap(True)
        self.geConnectionInfoLabel.setObjectName("geConnectionInfoLabel")
        self.horizontalLayout.addWidget(self.geConnectionInfoLabel)
        self.lfbGPSCount = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfbGPSCount.sizePolicy().hasHeightForWidth())
        self.lfbGPSCount.setSizePolicy(sizePolicy)
        self.lfbGPSCount.setMinimumSize(QtCore.QSize(0, 0))
        self.lfbGPSCount.setObjectName("lfbGPSCount")
        self.horizontalLayout.addWidget(self.lfbGPSCount)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lfbRecording.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.lfbRecording)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Select GPS-Device"))
        self.lfbCancelCoordinatesBtn.setText(_translate("Form", "STOP TRACKING"))
        self.lfbGetCoordinatesGtn.setText(_translate("Form", "START TRACKING"))
        self.geConnectionInfoLabel.setText(_translate("Form", "TextLabel"))
        self.lfbGPSCount.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "Messungen"))
