# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gerrit/Sites/lfb/qgis-gnavs-plugin/gnavs/gui/recording/toggle_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(814, 172)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lfbNavigationButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lfbNavigationButton.setFont(font)
        self.lfbNavigationButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbNavigationButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid #333;\n"
"    color: #555;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: yellow;\n"
"}\n"
"QPushButton:enabled{\n"
"    border:  2px solid green;\n"
"    background-color: green;\n"
"    color: #fff;\n"
"}")
        self.lfbNavigationButton.setCheckable(True)
        self.lfbNavigationButton.setChecked(True)
        self.lfbNavigationButton.setObjectName("lfbNavigationButton")
        self.horizontalLayout_3.addWidget(self.lfbNavigationButton)
        self.lfbPointButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lfbPointButton.setFont(font)
        self.lfbPointButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbPointButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid #333;\n"
"    color: #555;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: yellow;\n"
"}\n"
"QPushButton:enabled{\n"
"    border:  2px solid green;\n"
"    background-color: green;\n"
"    color: #fff;\n"
"}")
        self.lfbPointButton.setCheckable(True)
        self.lfbPointButton.setObjectName("lfbPointButton")
        self.horizontalLayout_3.addWidget(self.lfbPointButton)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lfbSettingsButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lfbSettingsButton.setFont(font)
        self.lfbSettingsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lfbSettingsButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid #333;\n"
"    color: #555;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: yellow;\n"
"}\n"
"QPushButton:enabled{\n"
"    border:  2px solid green;\n"
"    background-color: green;\n"
"    color: #fff;\n"
"}")
        self.lfbSettingsButton.setObjectName("lfbSettingsButton")
        self.horizontalLayout_3.addWidget(self.lfbSettingsButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lfbNavigationButton.setText(_translate("Form", "NAVIGATION"))
        self.lfbPointButton.setText(_translate("Form", "PUNKTAUFNAHME"))
        self.lfbSettingsButton.setText(_translate("Form", "SETTINGS"))
